# Site wide configuration

title: Andy Lindeman
locale: en_US
url: #http://andylindeman.com

# Jekyll configuration

permalink: /:title/
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Andy Lindeman
  avatar: http://www.gravatar.com/avatar/04ec66ce302551a608ec3a0451cfa1f2.png?s=400
  bio: "software development, tech operations, etc."
  email: 
  disqus-shortname: 
  twitter: alindeman
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: alindeman
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: andylindeman
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
